### PR TITLE
Update pacman.xml

### PR DESCRIPTION
**Pull request by francoism90**
`pacman.log` is/can be used to recover the system, it is not recommended to remove this log file:
https://wiki.archlinux.org/index.php/Pacman/Restore_local_database

### CODE REVIEW

**Comment by az0** [comment]
How big is the pacman,log file? Is it common for the pacman local database to be corrupt and require repair? Instead of removing the option, what about giving a (better) warning?

**Comment by francoism90** [comment]
@az0 On my workstation `pacman.log` is around 5,5M, first installed in the beginning of 2019. For most users doing daily upgrades I don't think the logfile will exceed 50M+ over the next few years, however this all depends on the user's interactions with pacman.

Arch Linux is a rolling distro so looking back in history can be important on upgrades. Although it isn't common the local database will become corrupted, tools allow to rebuild the system without the need of doing a re-installation/format.

However I agree about giving a (better) warning would be a better option, instead of removing this option like I suggested. :)

**Comment by az0** [comment]
>However I agree about giving a (better) warning would be a better option, instead of removing this option like I suggested. 

OK. How about this warning?

"This log file is required to repair the pacman local database if it becomes corrupt."

Feel free to change your PR to this, or let me know, and I will make the change.

**Comment by francoism90** [comment]
@az0 I'm Ok with your change, please make it happen as well. :)

**Pull request merged**
